import type { SiteConfig } from "@/lib/sites/config";

export const tivolidayTripConfig: SiteConfig = {
  slug: "tivoli-day-trip",
  name: "Tivoli Day Trip",
  domain: "tivoli-day-trip.com",
  description: "First-hand guide to Rome's street food — honest recommendations, no tourist traps.",
  heroImage: { src: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1600&q=80", alt: "Rome street food" },
  heroTitle: "Rome Street Food Tours",
  heroGoldWord: "Rome",
  heroSubtitle: "Authentic flavors, local neighborhoods",

  chips: [
    "Authentic",
    "Local Guides",
    "Small Groups",
    "No Tourist Traps",
    "Live Experience",
    "Market Walks",
    "Street Vendors",
    "Family-Friendly",
    "Hands-On Tasting",
    "Hidden Gems",
    "Neighborhood Focus",
    "Expert Tips",
    "Food Stories",
    "Cooking Skills",
    "Wine Pairing",
    "Seasonal Menu",
    "Photography Spots",
    "Cultural Deep-Dive",
    "Foodie Paradise",
    "Unforgettable Flavors",
  ],

  namesStrip: [
    { name: "Carbonara", href: "/tours/category/pasta" },
    { name: "Cacio e Pepe", href: "/tours/category/pasta" },
    { name: "Supplì", href: "/tours/category/street-food-classics" },
    { name: "Trapizzino", href: "/tours/category/street-food-classics" },
    { name: "Pizza al Taglio", href: "/tours/category/pizza" },
    { name: "Maritozzo", href: "/tours/category/gelato" },
    { name: "Gelato", href: "/tours/category/gelato" },
    { name: "Carciofi alla Giudia", href: "/neighborhoods/jewish-ghetto" },
    { name: "Amatriciana", href: "/tours/category/pasta" },
    { name: "Porchetta", href: "/tours" },
  ],

  sliderTitle: "Top Food Items to Try in Rome",

  categories: [
    {
      name: "Pizza",
      slug: "pizza",
      description: "Crispy pizza al taglio, bakery pizza bianca and Roman-style thin crust.",
      imageUrl: "https://images.unsplash.com/photo-1664309641932-0e03e0771b97",
      tourSlugs: [
        "pizza-al-taglio-suppli-tasting-tour",
        "trastevere-pizza-craft-beer-crawl",
        "roman-pizza-bianca-bakery-tour",
      ],
    },
    {
      name: "Pasta",
      slug: "pasta",
      description: "Carbonara, Cacio e Pepe, and other iconic Roman pasta dishes.",
      imageUrl: "https://images.unsplash.com/photo-1755594461640-b800c6bafdfa",
      tourSlugs: [
        "pasta-making-class-trastevere",
        "cacio-e-pepe-carbonara-tasting-walk",
        "roman-pasta-four-ways-dinner",
      ],
    },
    {
      name: "Beer & Wine",
      slug: "beer-and-wine",
      description: "Italian wines and local beers paired with authentic Roman cuisine.",
      imageUrl: "https://images.unsplash.com/photo-1783443800128-8893eac948bb",
      tourSlugs: ["rome-food-wine-tasting", "monti-food-wine-evening", "trastevere-food-wine-walk"],
    },
    {
      name: "Gelato",
      slug: "gelato",
      description: "Artisanal gelato from the best gelaterias in Rome, with espresso.",
      imageUrl: "https://images.unsplash.com/photo-1759314420838-36d3d881c81c",
      tourSlugs: ["roman-gelato-tasting-walk", "best-gelaterias-of-rome-tour", "gelato-espresso-crawl"],
    },
    {
      name: "Suppli & Street Food Classics",
      slug: "street-food-classics",
      description: "Fried Roman street food: suppli, trapizzino, and testaccio classics.",
      imageUrl: "https://images.unsplash.com/photo-1688458296759-91020b4ff2ba",
      tourSlugs: [
        "suppli-roman-street-snacks-tour",
        "trapizzino-fried-classics-walk",
        "testaccio-fried-food-crawl",
      ],
    },
  ],

  howWeChoose: [
    { title: "Authentic", description: "No tourist traps — only where Romans actually eat." },
    { title: "Local-Led", description: "Guides who live and eat in Rome every day." },
    { title: "Neighborhood-Based", description: "Explore real neighborhoods, not just landmarks." },
    { title: "Intimate Groups", description: "8–12 people max for a genuine connection." },
  ],

  placesTabs: [
    { name: "Testaccio Market", href: "/neighborhoods/testaccio" },
    { name: "Campo de' Fiori Market", href: "/neighborhoods/campo-de-fiori" },
    { name: "Trastevere", href: "/neighborhoods/trastevere" },
    { name: "Jewish Ghetto", href: "/neighborhoods/jewish-ghetto" },
    { name: "Trevi Fountain", href: "/blog" },
    { name: "Pantheon", href: "/blog" },
    { name: "Piazza Navona", href: "/blog" },
    { name: "Colosseum", href: "/blog" },
    { name: "Vatican Museums", href: "/blog" },
    { name: "Spanish Steps", href: "/blog" },
    { name: "Monti", href: "/neighborhoods/monti" },
    { name: "Prati", href: "/neighborhoods/prati" },
    { name: "San Lorenzo", href: "/neighborhoods/san-lorenzo" },
    { name: "Pigneto", href: "/neighborhoods/pigneto" },
    { name: "Villa Borghese", href: "/blog" },
    { name: "Circus Maximus", href: "/blog" },
    { name: "Piazza del Popolo", href: "/blog" },
    { name: "Via del Corso", href: "/blog" },
    { name: "Trionfale Market", href: "/neighborhoods/trionfale" },
    { name: "Garbatella", href: "/neighborhoods/garbatella" },
  ],

  metaDescription: "First-hand guide to Rome's street food — honest recommendations, no tourist traps.",
  contactEmail: "hello@tivoli-day-trip.com",
};
