import type { SiteConfig } from './config';

export const siteConfigs: Record<string, SiteConfig> = {
  'street-food-rome': {
    slug: 'street-food-rome',
    name: 'Street Food Rome',
    domain: 'streetfoodrome.com',
    description: 'First-hand guide to Rome\'s street food — honest recommendations, no tourist traps.',
    heroImage: { src: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1600&q=80', alt: 'Rome street food' },
    heroTitle: 'Rome Street Food Tours',
    heroSubtitle: 'Authentic flavors, local neighborhoods',
    accentWord: 'Rome',
    metaDescription: 'First-hand guide to Rome\'s street food — honest recommendations, no tourist traps.',
    contactEmail: 'hello@streetfoodrome.com',
  },
  'underground-colosseum': {
    slug: 'underground-colosseum',
    name: 'Underground Colosseum',
    domain: 'undergroundcolosseum.com',
    description: 'Underground and arena-floor Colosseum tours compared.',
    heroImage: { src: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1600&q=80', alt: 'Colosseum' },
    heroTitle: 'Underground & Arena Floor Tours',
    heroSubtitle: 'Access beyond the typical experience',
    accentWord: 'Underground',
    metaDescription: 'A first-hand guide to Colosseum underground and arena-floor access tours.',
    contactEmail: 'hello@undergroundcolosseum.com',
  },
  'private-vatican': {
    slug: 'private-vatican',
    name: 'Private Vatican',
    domain: 'privatevatican.com',
    description: 'Early-access and private Vatican tours compared.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Vatican' },
    heroTitle: 'Private Vatican Tours',
    heroSubtitle: 'Early access and exclusive experiences',
    accentWord: 'Private',
    metaDescription: 'Independent guide to Vatican early-access and private tours.',
    contactEmail: 'hello@privatevatican.com',
  },
  'pompeii-day-trip': {
    slug: 'pompeii-day-trip',
    name: 'Pompeii Day Trip',
    domain: 'pompeii-day-trip.com',
    description: 'Pompeii day-trip planning from Rome.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Pompeii' },
    heroTitle: 'Pompeii Day Trips',
    heroSubtitle: 'From Rome, Naples, and beyond',
    accentWord: 'Pompeii',
    metaDescription: 'Honest, first-hand Pompeii day-trip planning by origin city.',
    contactEmail: 'hello@pompeii-day-trip.com',
  },
  'rome-vespa': {
    slug: 'rome-vespa',
    name: 'Rome Vespa',
    domain: 'romeVespa.com',
    description: 'Vespa and sidecar tours in Rome.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Vespa' },
    heroTitle: 'Rome Vespa Tours',
    heroSubtitle: 'Guided, self-drive & sidecar routes',
    accentWord: 'Vespa',
    metaDescription: 'First-hand guide to Vespa and sidecar tours in Rome.',
    contactEmail: 'hello@romeVespa.com',
  },
  'golf-cart-rome': {
    slug: 'golf-cart-rome',
    name: 'Golf Cart Rome',
    domain: 'golfcartrome.com',
    description: 'Golf cart tours in Rome.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Golf cart' },
    heroTitle: 'Rome Golf Cart Tours',
    heroSubtitle: 'Guided & customized itineraries',
    accentWord: 'Golf',
    metaDescription: 'First-hand guide to golf cart tours in Rome.',
    contactEmail: 'hello@golfcartrome.com',
  },
  'cooking-in-rome': {
    slug: 'cooking-in-rome',
    name: 'Cooking in Rome',
    domain: 'cookinginrome.com',
    description: 'Rome cooking classes.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Cooking' },
    heroTitle: 'Rome Cooking Classes',
    heroSubtitle: 'Pasta, pizza & market-to-table',
    accentWord: 'Cooking',
    metaDescription: 'First-hand guide to Rome cooking classes.',
    contactEmail: 'hello@cookinginrome.com',
  },
  'rome-pizza-class': {
    slug: 'rome-pizza-class',
    name: 'Rome Pizza Class',
    domain: 'romepizzaclass.com',
    description: 'Rome pizza-making classes.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Pizza' },
    heroTitle: 'Rome Pizza-Making Class',
    heroSubtitle: 'Hands-on, wood-fired technique',
    accentWord: 'Pizza',
    metaDescription: 'Learn real Roman pizza-making hands-on.',
    contactEmail: 'hello@romepizzaclass.com',
  },
  'tiramisu-class': {
    slug: 'tiramisu-class',
    name: 'Tiramisu Class',
    domain: 'tiramisuclass.com',
    description: 'Tiramisu-making classes in Rome.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Tiramisu' },
    heroTitle: 'Tiramisu Class Rome',
    heroSubtitle: 'Hands-on dessert-making',
    accentWord: 'Tiramisu',
    metaDescription: 'Learn to make real tiramisu hands-on in Rome.',
    contactEmail: 'hello@tiramisuclass.com',
  },
  'tuscany-day-trip': {
    slug: 'tuscany-day-trip',
    name: 'Tuscany Day Trip',
    domain: 'tuscany-day-trip.com',
    description: 'Tuscany day-trip planning.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Tuscany' },
    heroTitle: 'Tuscany Day Trips',
    heroSubtitle: 'From Florence, Siena & beyond',
    accentWord: 'Tuscany',
    metaDescription: 'First-hand Tuscany day-trip guide.',
    contactEmail: 'hello@tuscany-day-trip.com',
  },
  'amalfi-day-trip': {
    slug: 'amalfi-day-trip',
    name: 'Amalfi Day Trip',
    domain: 'amalfi-day-trip.com',
    description: 'Amalfi Coast day-trip planning.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Amalfi' },
    heroTitle: 'Amalfi Day Trips',
    heroSubtitle: 'Positano, Ravello, Salerno & more',
    accentWord: 'Amalfi',
    metaDescription: 'First-hand Amalfi Coast day-trip guide.',
    contactEmail: 'hello@amalfi-day-trip.com',
  },
  'tivoli-day-trip': {
    slug: 'tivoli-day-trip',
    name: 'Tivoli Day Trip',
    domain: 'tivoli-day-trip.com',
    description: 'Tivoli day-trip planning from Rome.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Tivoli' },
    heroTitle: 'Tivoli Day Trips',
    heroSubtitle: 'Villa d\'Este & Hadrian\'s Villa',
    accentWord: 'Tivoli',
    metaDescription: 'First-hand Tivoli day-trip guide from Rome.',
    contactEmail: 'hello@tivoli-day-trip.com',
  },
  'naples-street-food': {
    slug: 'naples-street-food',
    name: 'Naples Street Food',
    domain: 'naplesstreetfood.com',
    description: 'Naples street food tours.',
    heroImage: { src: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80', alt: 'Naples' },
    heroTitle: 'Naples Street Food Tours',
    heroSubtitle: 'Pizza, markets & Spaccanapoli',
    accentWord: 'Naples',
    metaDescription: 'First-hand Naples food tours.',
    contactEmail: 'hello@naplesstreetfood.com',
  },
};

export function getSiteConfig(slug: string): SiteConfig | undefined {
  return siteConfigs[slug];
}
